### ISSUE TITLE
白黑切换没有变化的问题解决

### ISSUE THREAD

**Issue by BraveheartHu** [xiaolai/slidology-from-xiaolai#3]
老师，《如何把 Microsof Word 当作白板教学工具？》文档中的黑白字体切换没有变化，需要进行修改：
修改前：
Sub Macro_Selection_Font_Color_BLACK_WHITE_SWITCH()
    If Selection.Font.ColorIndex = wdWhite Then
        Selection.Font.ColorIndex = wdWhite
    Else
        Selection.Font.ColorIndex = wdBlack
End Sub

修改后：
Sub Macro_Selection_Font_Color_BLACK_WHITE_SWITCH()
    If Selection.Font.ColorIndex = wdBlack Then
        Selection.Font.ColorIndex = wdWhite
    Else
        Selection.Font.ColorIndex = wdBlack
End Sub

**Comment by jincai** [comment]
这个少了一个End If
